[package]
name = "wlbreaktimer"
version = "0.1.1"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"
wayland-client = "0.31.8"
wayland-protocols = { version = "0.32.8", features = ["client"] }
